root = "."
tmp_dir = "build"

[build]
cmd = "go build -o ./build/ ./cmd/server/main.go"
full_bin = "cd ./build && PORT=8000 ./main"
exclude_unchanged = true
include_ext = ["go", "tpl", "tmpl", "html"]